# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KZVa7gavbII2CmuRvF2Jf8yA08pGRnU6
"""

def func(nums):
  res = [1]
  for i in range(len(nums)-1):
    res.append(res[-1]*nums[i])
  postfix = 1
  for i in range(len(res)-1,-1,-1):
    res[i] *= postfix
    postfix *= nums[i]
  return res

print(func([1,2,3,4]))

