# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHm_Y6TvVSSVaL3yC90X7n9qpvmx2PSs
"""

import re
import nltk
import string
!pip install transformers

import transformers

with open('nlp.txt') as f:
    lines = f.read().replace('\n','')

lines

lines[0]

classes = ['Ambrette Seed',
'Apple Cinnamon Granola',
'Arizona Seasoning', 
'Americano Coffee',
'Baby Abalone',
'Cadbury Double Decker Chocolate Bar',
'Campari Tomato',
'Celery Soup',
'Chia Meal',
'Crunch Bars',
'Cardamom',
'Giardiniera',
'Hog Maw',
'Mccormick Montreal Steak Seasoning',
'Muesli',
'Mulberry',
'Munch Chocolate',
'Murukku Packet',
'Mango',
'Organic Maize',
'Organic Peruvian Groundcherry',
'Organic Tartar Cream',
'Orange Extract',
'Pickled Cauliflower',
'Pork Chump Chops',
'Pork Lungs',
'Pork Tripe',
'Peanut Butter',
'Smokies Sausage',
'Snickers Spread',
'Strawberry Gelatin',
'Salmon',
'Tomato',
'Tamarind',
'Vegan Carob Chips',
'Vegan Chicken Strips',
'Vegan Chorizo',
'Vegan Marshmallow',
'Vegan Puff Pastry Sheet',
'Vegan Semisweet Chocolate Chips',
'Vegan White Cake',
'Vegetable Stock',
'Vinegar']

"""Basic Data Preprocessing

removing numbers
"""

def remove_numbers(text):
    result = re.sub(r'\d+', '', text)
    return result

lines=remove_numbers(lines)

#converting to lowercase
lines=lines.lower()

#remove punctuation
def remove_punctuation(text):
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

lines=remove_punctuation(lines)

lines

"""Applying pre-trained zero shot classification"""

classifier = transformers.pipeline("zero-shot-classification",model="facebook/bart-large-mnli")
results = classifier(lines, classes,multi_label=True)

import pandas as pd
df = pd.DataFrame({'Label':results["labels"],"Score":results["scores"]})
df["Rank"] = df.index + 1
df

